### ISSUE TITLE
Caderno para anotar o inventário do armário (retirada/devolução)

### ISSUE THREAD

**Issue by cesareds** [ColmeiaUDESC/Arquivo#10]
Muniz disse que seria MUITO importante, então ta aí pra ser feito

**Comment by Seekke** [comment]
Tem que ver pq o Gilmário deu aquele papo lá de que não era pra emprestar nada, mas de qualquer forma ia ser importante pra checar se nada foi roubado ou perdido numa visita escolar ou qualquer outra atividade

**Comment by Seekke** [comment]
Oficialmente vetado 👍

**Comment by Seekke** [comment]
Oficialmente vetado 👍
